BUILD_ROOT = "$(MAKEDIR)\target"
RELEASE_ROOT = "$(BUILD_ROOT)\release"
BIN_TARGET = "rtfm.exe"
RTFM = "$(RELEASE_ROOT)\$(BIN_TARGET)"

all: $(BIN_TARGET)

clean:
	@cargo clean

install:
	mkdir "%%PROGRAMFILES%%\rtfm"
	copy /Y "$(RTFM)"" "%%PROGRAMFILES%%\rtfm"

uninstall:
	del /Q "%%PROGRAMFILES%%\rtfm"
	rmdir /S /Q "%%PROGRAMFILES%%\rtfm"

$(BIN_TARGET):
	@cargo build --release
