.TH rtfm 1  "November 3, 2017" "version 1.0" "USER COMMANDS"
.SH NAME
rtfm - read the friendly manual
.SH SYNOPSIS
.TP
.B rtfm [no additional flags]
.TP
.TP
.B rtfm --help
.TP
.B rtfm [
.I 
program_name
]
.SH DESCRIPTION
.TP
The program rtfm is a computer program that prints out information of places to look for documentation for any unfamiliar computer program you may encounter. If you are not sure how to work with a particular program or third-party piece of software, rtfm will point you in the right direction. It is particularly effective for the most common questions for a given piece of software. Systems administrators will find this tool useful as part of their standard loadout for new user systems and shell environments.
.PP
.SH EXAMPLES
.TP
Display a friendly message directing you to relevant information about your program.
.B rtfm
.TP
Call up the manual for the program "rtfm"
.B rtfm rtfm
.TP
Get some help
.B rtfm --help
.PP
.SH AUTHOR
Written by Christopher Blanchard.
.SH COPYRIGHT
Copyright © 2017 Christopher Blanchard. License GPLv3+: GNU GPL version 3 or 
later <http://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it.  There is NO WARRANTY, to the extent permitted 
by law.
 